version: '3'

services:
  lotto:
    build:
      context: .
      dockerfile: dockerfile
    image: lucky-numbers
    container_name: lucky-numbers
    ports:
      - 3000:3000

    env_file: ./.env
    restart: always
